service:
  host: 0.0.0.0
  port: 8889
  SECRET_KEY: KLKey
  enable_security: false

log:
  file_name: ilens_utility_elm_client
  path: logs/
  level: DEBUG

mongo_db:
  host: localhost
  port: 27017
  database_name: ilens_utility_elm_client

auth:
  url: "https://www.googleapis.com/oauth2/v3/tokeninfo?id_token="